version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: roadwatch-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roadwatch-backend
    restart: unless-stopped
    environment:
      APP_NAME: RoadWatch AI API
      APP_ENV: production
      DEMO_MODE: "true"
      API_HOST: 0.0.0.0
      API_PORT: 8000
      FRONTEND_ORIGIN: "*"
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: roadwatch_ai
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
