const roadSegments = [
  {
    id: 'road-001',
    name: 'Sardar Patel Road',
    ward: 'Adyar',
    polyline: [
      { lat: 12.9928, lng: 80.2297 },
      { lat: 12.9941, lng: 80.2364 },
      { lat: 12.9968, lng: 80.2438 },
    ],
    roadHealthScore: 38,
    color: 'red',
    nearbyIssues: 14,
    recentComplaints: 9,
  },
  {
    id: 'road-002',
    name: 'OMR - Tidel Stretch',
    ward: 'Perungudi',
    polyline: [
      { lat: 12.9764, lng: 80.2496 },
      { lat: 12.9708, lng: 80.2522 },
      { lat: 12.9651, lng: 80.2549 },
    ],
    roadHealthScore: 61,
    color: 'yellow',
    nearbyIssues: 7,
    recentComplaints: 5,
  },
  {
    id: 'road-004',
    name: 'GST Road - Guindy Junction',
    ward: 'Guindy',
    polyline: [
      { lat: 13.0085, lng: 80.2042 },
      { lat: 13.0032, lng: 80.2021 },
      { lat: 12.9987, lng: 80.1998 },
    ],
    roadHealthScore: 46,
    color: 'red',
    nearbyIssues: 12,
    recentComplaints: 11,
  },
  {
    id: 'road-005',
    name: 'ECR Link Road',
    ward: 'Thiruvanmiyur',
    polyline: [
      { lat: 12.9846, lng: 80.2622 },
      { lat: 12.9799, lng: 80.2668 },
      { lat: 12.9754, lng: 80.2717 },
    ],
    roadHealthScore: 74,
    color: 'green',
    nearbyIssues: 4,
    recentComplaints: 2,
  },
];

const roadNetworkItems = [
  {
    id: 'nh-45',
    name: 'NH 45',
    type: 'NH',
    route: 'Chennai - Guduvanchery - Chengalpattu - Villupuram - Trichy - Dindigul',
    districts: ['Chennai', 'Chengalpattu', 'Villupuram', 'Tiruchirappalli', 'Dindigul'],
    length_km: 368,
    year: 1956,
    contractor: 'Dilip Buildcon Ltd.',
    budget_crore: 3312,
    condition: 'Good',
    issues: ['Urban Encroachments', 'Minor Cracks', 'Widening pending'],
    summary: 'NH | Good | 368 km',
  },
  {
    id: 'sh-49',
    name: 'State Highway 49',
    type: 'SH',
    route: 'Chennai - Mahabalipuram Coastal Belt',
    districts: ['Chennai', 'Chengalpattu'],
    length_km: 65,
    year: 1984,
    contractor: 'Tamil Nadu Roads Board',
    budget_crore: 820,
    condition: 'Moderate',
    issues: ['Surface wear', 'Monsoon patchwork', 'Drainage issues'],
    summary: 'SH | Moderate | 65 km',
  },
  {
    id: 'mdr-001',
    name: 'Sardar Patel Road Connector',
    type: 'MDR',
    route: 'Adyar - Saidapet link road',
    districts: ['Chennai'],
    length_km: 12,
    year: 1998,
    contractor: 'Metro CivilWorks Pvt Ltd.',
    budget_crore: 54,
    condition: 'Poor',
    issues: ['Potholes', 'Broken shoulders', 'Drain cover damage'],
    summary: 'MDR | Poor | 12 km',
  },
  {
    id: 'mdr-002',
    name: 'OMR - Tidel Stretch',
    type: 'MDR',
    route: 'Perungudi - Taramani service road',
    districts: ['Chennai'],
    length_km: 9,
    year: 2004,
    contractor: 'South Corridor Infra LLP',
    budget_crore: 71,
    condition: 'Moderate',
    issues: ['Lane markings faded', 'Small cracks'],
    summary: 'MDR | Moderate | 9 km',
  },
  {
    id: 'nh-48',
    name: 'NH 48',
    type: 'NH',
    route: 'Chennai - Ranipet - Vellore - Krishnagiri',
    districts: ['Chennai', 'Tiruvallur', 'Vellore', 'Ranipet', 'Krishnagiri'],
    length_km: 210,
    year: 1955,
    contractor: 'GR Infraprojects Ltd.',
    budget_crore: 2310,
    condition: 'Good',
    issues: ['Toll Plaza Queues', 'Faded Lane Markings'],
    summary: 'NH | Good | 210 km',
  },
];

const budgets = [
  {
    road_id: 'road-001',
    project_id: 'CHN-2025-ADY-11',
    allocated_inr: 5000000,
    spent_inr: 4700000,
    contractor: 'Metro CivilWorks Pvt Ltd',
    last_repair_date: '2025-12-03',
    expected_score: 78,
    actual_score: 38,
    transparency_note: 'Transparency alert: INR 5,000,000 allocated but score is 38/100',
  },
  {
    road_id: 'road-002',
    project_id: 'CHN-2025-PRG-07',
    allocated_inr: 3500000,
    spent_inr: 3260000,
    contractor: 'South Corridor Infra LLP',
    last_repair_date: '2025-11-18',
    expected_score: 72,
    actual_score: 61,
    transparency_note: 'Moderate mismatch between expected and AI-observed condition',
  },
];

const contractors = [
  {
    id: 'con-001',
    name: 'Metro CivilWorks Pvt Ltd',
    company: 'Metro Construction',
    project_status: 'Active',
    overall_rating: 3.8,
    total_reviews: 24,
    trusted_badge: 'silver',
    public_transparency_score: 72.5,
    complaint_count: 3,
    roads_managed: ['road-001', 'nh-45'],
    profile_image_url: '',
    reviews: [
      {
        id: 'rev-001', user_id: 'user-001', user_name: 'Arjun K', rating: 5,
        sentiment: 'positive', review_text: 'Excellent work on Sardar Patel Road.', emotion_emoji: '😊',
        timestamp: '2026-05-10T14:30:00Z', is_spam_detected: false, helpful_count: 12,
      },
      {
        id: 'rev-002', user_id: 'user-002', user_name: 'Priya M', rating: 3,
        sentiment: 'neutral', review_text: 'Good quality but delayed completion.', emotion_emoji: '😐',
        timestamp: '2026-05-08T10:15:00Z', is_spam_detected: false, helpful_count: 8,
      },
    ],
  },
  {
    id: 'con-002',
    name: 'South Corridor Infra LLP',
    company: 'Corridor Infrastructure',
    project_status: 'Completed',
    overall_rating: 4.2,
    total_reviews: 18,
    trusted_badge: 'gold',
    public_transparency_score: 85.0,
    complaint_count: 1,
    roads_managed: ['road-002', 'sh-49'],
    profile_image_url: '',
    reviews: [
      {
        id: 'rev-004', user_id: 'user-004', user_name: 'Anita S', rating: 5,
        sentiment: 'positive', review_text: 'Outstanding project execution.', emotion_emoji: '😊',
        timestamp: '2026-05-09T16:45:00Z', is_spam_detected: false, helpful_count: 15,
      },
    ],
  },
];

const complaintReports = [
  {
    id: 'cmp-2026-0001',
    user_email: 'demo@roadwatch.local',
    road_id: 'road-001',
    title: 'Potholes near bus stop',
    description: 'Multiple deep potholes near bus stop causing bike skids.',
    category: 'Pothole',
    image_ref: 'demo_pothole_1.jpg',
    location: { lat: 12.9946, lng: 80.2371 },
    timestamp: '2026-04-28T08:41:00Z',
    status: 'In Progress',
    authority_ticket: 'CCMC-11408',
    recommended_department: 'Highways Department',
    routing_reason: 'Pothole repair and road surfacing issues are handled by highways.',
    complaint_letter: 'Please inspect and repair the potholes near the bus stop on Sardar Patel Road.',
    sent_to_authority: true,
    delivered_to_authority: true,
    read_by_authority: false,
    sent_at: '2026-04-28T09:05:00Z',
    delivered_at: '2026-04-28T09:15:00Z',
    read_at: null,
    timeline: [
      { status: 'Filed', at: '2026-04-28T08:41:00Z', note: 'Complaint auto-filed from RoadWatch AI' },
      { status: 'Sent', at: '2026-04-28T09:05:00Z', note: 'Complaint sent to Highways Department' },
      { status: 'Delivered', at: '2026-04-28T09:15:00Z', note: 'Complaint letter delivered to the department inbox' },
    ],
  },
  {
    id: 'cmp-2026-0002',
    user_email: 'demo@roadwatch.local',
    road_id: 'road-002',
    title: 'Waterlogging on service road',
    description: 'Water accumulates for hours after light rain.',
    category: 'Waterlogging',
    image_ref: 'demo_waterlogging.jpg',
    location: { lat: 12.9695, lng: 80.2532 },
    timestamp: '2026-04-30T11:05:00Z',
    status: 'Pending',
    authority_ticket: 'PENDING',
    recommended_department: 'Municipal Corporation',
    routing_reason: 'Drainage and storm-water issues are handled by the local body.',
    complaint_letter: 'Please clear the waterlogging and inspect the drainage line.',
    sent_to_authority: false,
    delivered_to_authority: false,
    read_by_authority: false,
    sent_at: null,
    delivered_at: null,
    read_at: null,
    timeline: [
      { status: 'Filed', at: '2026-04-30T11:05:00Z', note: 'Complaint filed through RoadWatch AI' },
    ],
  },
];

module.exports = {
  roadSegments,
  roadNetworkItems,
  budgets,
  contractors,
  complaintReports,
};
